fetch_price:
  every: 60s
  class: FetchPriceJob
  args:
  description: Grabs newest prices from public API of Coinbase

send_price:
  every: 60s
  class: SendPriceJob
  args:
  description: Send to client
